### ISSUE TITLE
[NEW] Send.cm

### ISSUE THREAD

**Issue by TomWareC** [xHyroM/OSList#18]
**Install.wim**
**URL**
https://send.cm/d/3UkB

**Type**
Windows (x64)

**Version**
Win 11 | Build 22000

**Fast**
true

MD5: 53ee49a0979a6fdcdec06bd4ca68c40e

**Install.esd**
**URL**
https://send.cm/d/3UkC

**Type**
Windows (x64)

**Version**
Win 11 | Build 22000

**Fast**
true

MD5: 0df25ce8d22c155c81336ccd3df1f989

**Comment by xHyroM** [comment]
https://github.com/xHyroM/OSList/commit/75dbf6f72028df7468c90b0fc74cef129c9de804

**Comment by TomWareC** [comment]
I noticed that Send CM says that Download session expired. So the problem should be solved if they were in this form: https://send.cm/d/3UkB, https://send.cm/d/3UkC
![image](https://user-images.githubusercontent.com/72803682/124111233-97947c00-da58-11eb-9a04-756920348974.png)
