### ISSUE TITLE
[NEW] Windows 8.1 with Update 3 (Core & Pro) x64 (Send.cm)

### ISSUE THREAD

**Issue by TomWareC** [xHyroM/OSList#21]
**URL**
https://send.cm/d/3Vz6

**Type**
Windows (x64)

**Version**
Win 8.1 | Build 9600

**Fast**
true

MD5: e0d4594e56c0545d379340e0db9519a5

**Comment by xHyroM** [comment]
https://github.com/xHyroM/OSList/commit/666c24fbf4686035215ff19fffbf991f5229849b
