### ISSUE TITLE
[BROKEN] Send.cm - Win 11 | Build 22000

### ISSUE THREAD

**Issue by TomWareC** [xHyroM/OSList#22]
**Link**
Win 11 | Build 22000 https://cloud3.send.cm/d/dbytwwkm6gosj4l4xj2v7h5a3savh6xmxo5siitw4erj4caz6moyljmud3lns2l5fdio6ghe/22000.51.210617-2050.CO_RELEASE_SVC_PROD2_CLIENTPRO_OEMRET_X64FRE_EN-US_WIM.ISO

Win 11 | Build 22000
https://cloud3.send.cm/d/dbysiwkm6gosj4l4xj2vlcnuy5zaxfey4zcfz5znnkk3caw2vr3kouafqk7dclapvqesbose/22000.51.210617-2050.CO_RELEASE_SVC_PROD2_CLIENTPRO_OEMRET_X64FRE_EN-US_ESD.ISO

**Problem**
Download session expired. The problem should be solved if they were in this form: https://send.cm/d/3UkB, https://send.cm/d/3UkC
![image](https://user-images.githubusercontent.com/72803682/124111233-97947c00-da58-11eb-9a04-756920348974.png)

**Comment by xHyroM** [comment]
https://github.com/xHyroM/OSList/commit/93692061bfaa2e55455a4ca978789c0dc7e44bc3 fixed
