### ISSUE TITLE
[NEW] Windows 8.1 with Update 3 (Core & Pro) x64 - GoFile

### ISSUE THREAD

**Issue by TomWareC** [xHyroM/OSList#23]
**URL**
https://gofile.io/d/klNqHk

**Type**
Windows (x64)

**Version**
Win 8.1 | Build 9600

**Fast**
true

MD5: e0d4594e56c0545d379340e0db9519a5

**Comment by xHyroM** [comment]
https://github.com/xHyroM/OSList/commit/5162d60cdff0f9f26015f61f3882c9577850008c
