### ISSUE TITLE
[NEW] Windows Neptune 5111.1 - Send.cm

### ISSUE THREAD

**Issue by TomWareC** [xHyroM/OSList#25]
**URL**
https://send.cm/d/3WCI

**Type**
Windows

**Version**
Win Neptune | Build 5111.1

**Fast**
true

MD5: afce6bcc014bfe5eb4dfcabd23247688

**Comment by xHyroM** [comment]
https://github.com/xHyroM/OSList/commit/5162d60cdff0f9f26015f61f3882c9577850008c
