### ISSUE TITLE
[NEW] Windows Neptune 5111.1 - Mega.nz

### ISSUE THREAD

**Issue by TomWareC** [xHyroM/OSList#26]
**URL**
https://mega.nz/file/bhEkgZ4B#X486TU4V6m4UlxW1k15hSdRPWrQgHV9koB1Z5s-6BCE

**Type**
Windows

**Version**
Win Neptune | Build 5111.1

**Fast**
true

MD5: afce6bcc014bfe5eb4dfcabd23247688

**Comment by xHyroM** [comment]
https://github.com/xHyroM/OSList/commit/5162d60cdff0f9f26015f61f3882c9577850008c
