### ISSUE TITLE
[NEW] Windows Longhorn (Vista) 4051 - Send.cm

### ISSUE THREAD

**Issue by TomWareC** [xHyroM/OSList#28]
**URL**
https://send.cm/d/3WD8

**Type**
Windows

**Version**
Win Longhorn (Vista) | Build 4051

**Fast**
true

MD5: 0c17c336b0ba37b1d5f9a360006630cc

**Comment by xHyroM** [comment]
https://github.com/xHyroM/OSList/commit/5162d60cdff0f9f26015f61f3882c9577850008c
