### ISSUE TITLE
[NEW] Windows 10 build 18922 - Send.cm

### ISSUE THREAD

**Issue by TomWareC** [xHyroM/OSList#31]
**URL**
https://send.cm/d/3WFk

**Type**
Windows (x64)

**Version**
Win 10 | Build 18922

**Fast**
true

MD5: c317d3920e78d979d9a551ab79a76b93

**Comment by xHyroM** [comment]
https://github.com/xHyroM/OSList/commit/db91825711da83b31513a25fc9484bf48fa016ba
