### ISSUE TITLE
[NEW] Windows 2.03

### ISSUE THREAD

**Issue by slovak-cat** [xHyroM/OSList#33]
**URL** 
<https://winworldpc.com/download/0474c84d-d5c4-11eb-9de1-0200008a0da4/from/c3ae6ee2-8099-713d-3411-c3a6e280947e>

**Type**
Windows

**Version**
Microsoft Windows 2.03 (3.5-720k) | Retail Build

**Fast**
true

**Checksum**
`46bc99ab7f736ea193f07c7c6b46f32e1c179a5a`

**Comment by slovak-cat** [comment]
Req: 

> DOS 5 or later


Instalation File 

>`WIN200.BIN`

**Comment by xHyroM** [comment]
Thx, https://github.com/xHyroM/OSList/commit/a3a814562f9ead8344fa1e494131548c486158f7
